import {ServerApp} from '@server/app/ServerApp';
import {UsersServerController} from '@module/users/UsersServerController';
import {ProjectsServerController} from '@module/projects/ProjectsServerController';
import {TeamsServerController} from '@module/teams/TeamsServerController';const server = new ServerApp();
const app = server.getApp();
const Users = new UsersServerController(app, server.store);
const Projects = new ProjectsServerController(app, server.store);
const Teams = new TeamsServerController(app, server.store);
server.start();
export { app };
